language: python
python:
  - 3.7

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - python --version
  - pip install -U pip
  - pip install pytest

script: pytest
  
jobs:
  include:
      - stage: build
        script: 
          - docker build -t smartvit/admin-service .
      - stage: test
        script: 
          - flake8
          # - pytest
          # - coverage run -m pytest
          # - coverage xml
          - cd app/ && behave
# after_success:
  # - python-codacy-coverage -r coverage.xml

